review
Atasik/blog-customizer pull request #1
Opened 2024-05-04 07:23 UTC by Atasik

2024-05-04 11:03 UTC, olgalatkina requested changes
Добрый день!

**У вас получилась хорошая работа:**
- Полностью реализован весь функционал.
- Проект соответствует макету на сколько это возможно.
- Для условного добавления css-классов спользуется библиотека `clsx`.
- Логика закрытия сайдбара по клику вне сайдбара вынесена в кастомный хук.
- Обработчик сохранения данных вызывается при отправке формы.
- Код хорошо типизирован.

**Но есть несколько моментов, которые надо поправить:**
- [ ] При помощи рефа нужно получать доступ к внешнему диву, чтобы не было бага с закрытием формы.
- [ ] Не допускается использовать для значения по умолчанию элементы с нулевым индексом из массивов свойств. 
- [ ] Код должен быть отформатирован. В проектах специально настраивают линтеры и форматеры, чтобы для всех членов команды код выглядел одинаково. Не пренебрегайте командами из package.json перед тем как пушить код. 

**Правки можно лучше остаются на ваше усмотрение:**
- [ ] С очень большой осторожностью стоит обращаться с кодом библиотечных компонентов, особенно, если они шарятся на большой проект и переиспользуются в разных местах проекта. Таким образом можно поломать код совсем в другом месте и ваш коллега даже не сразу поймёт, почему это произошло. Стоит вернуть истории в папки с библиотечными компонентами.
- [ ] Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.ts`x.
- [ ] Для одиночных селекторов не стоит использовать библиотеку `clsx `.
- [ ] Отладочные выводы в консоль лучше удалить 
- [ ] Вы довольно много изменили в css. Надеюсь, вам понравится интересная задача: убрать горизонтальную прокрутку у сайдбара и дыру в фоне: https://disk.yandex.ru/d/NLJNChQ-Ns5rcg
 
Успешного рефакторинга!

2024-05-04 11:03 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +	useEffect(() => {
**Можно лучше:**
Отладочные выводы в консоль лучше удалить вместе с `useEffect`.

2024-05-04 11:03 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +			className={clsx(styles.container, {[styles.container_open]: isOpenForm})}
**Отлично:**
Замечательно, что для условного добавления css-классов используется библиотека `clsx`.

2024-05-04 11:03 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +				e.stopPropagation()
**Можно лучше:**
В этом проекте вполне можно обойтись без использования `stopPropagation`

2024-05-04 11:03 UTC, olgalatkina commented on src/index.tsx
>  			className={clsx(styles.main)}
**Можно лучше:**
Для одиночных селекторов не стоит использовать библиотеку `clsx`, лучше исправить этот момент здесь и в компоненте `Article`.

2024-05-04 11:03 UTC, olgalatkina commented on src/index.tsx
>  const App = () => {
**Можно лучше:**
Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.

2024-05-04 11:03 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +					onSubmit={formSubmitHandler}
**Отлично:**
Здорово, что обработчик сохранения данных вызывается при отправке формы.

2024-05-04 11:03 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +				ref={rootRef}
**Надо исправить:**
В реф нужно получить доступ к внешнему диву, который заменит `React.Fragment`

2024-05-04 11:03 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const formSubmitHandler = (e: SyntheticEvent) => {
**Можно лучше:**
Для типизации события  формы лучше использовать `FormEvent<HTMLFormElement>`
Замечание относится ко всем таким обработчикам.

2024-05-04 11:03 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +		setNewFontColor(fontColors[0]);
**Надо исправить:** 
Настройки статьи по умолчанию описаны в объекте `defaultArticleState`  в файле `constants/articleProps.ts` стартеркита. В проекте нужно использовать значения из этого объекта как настройки по умолчанию, как для самой статьи, так и как начальные значения полей форм.

Не допускается использовать для значения по умолчанию элементы с нулевым индексом из массивов свойств. То что настройки по умолчанию имеют именно нулевой индекс можно считать просто совпадением и это может измениться в любой момент.

2024-05-04 11:03 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	useOutsideClickClose({
**Отлично:**
Здорово, что попробовали применить кастомный хук!

Можете попробовать другое готовое решение, в нём так же реализовано закрытие по `Escape`:
```
import { useEffect } from "react";

type TUseClose = {
  isOpen: boolean;
  onClose: () => void;
  rootRef: React.RefObject<HTMLElement>;
};

// Кастомные хуки всегда должны начинаться с глагола `use`, чтобы реакт понял, что это хук. 
// Он следит за их вызовами
export function useClose({isOpen, onClose, rootRef}: TUseClose) {
  useEffect(() => {
    if (!isOpen) return; // останавливаем действие эффекта, если закрыто
   
    function handleClickOutside(event: MouseEvent) {
      const { target } = event;
      
      const isOutsideClick =
        target instanceof Node && // проверяем, что это `DOM`-элемент
        rootRef.current &&
        !rootRef.current.contains(target); // проверяем, что кликнули на элемент, который находится не внутри блока
      if (isOutsideClick) {
        onClose();
      }
    }

    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        onClose();
      }
    };

    document.addEventListener("keydown", handleEscape);
    document.addEventListener("mousedown", handleClickOutside);

    //  Обязательно удаляем обработчики в `clean-up`- функции
    return () => {
      document.removeEventListener("keydown", handleEscape);
      document.removeEventListener("mousedown", handleClickOutside);
    };
    
    // Обязательно следим за `isOpen`, чтобы срабатывало только при открытии, 
    // а не при любой перерисовке компонента
  }, [isOpen, onClose, rootRef]);
}
```

Этот код помещают в отдельный файл `useClose.ts` в папке `hooks` на одном уровне с папкой `components` и импортируют хук туда, где нужно.
Теперь его можно использовать в любом компоненте (попапе, меню и тд), которому нужно установить эти обработчики.

Пример того, как это использовать:
```
// Создаем `ref` для формы и указываем его на внешнем блоке с формой
const formRef = useRef<HTMLElement | null>(null);
    
useClose({
    isOpen,
    onClose: () => setIsOpen(false),
    rootRef: formRef,
});

2024-05-04 19:13 UTC, Atasik commented on src/components/arrow-button/ArrowButton.tsx
> +	useEffect(() => {
done

2024-05-04 19:13 UTC, Atasik commented on src/components/arrow-button/ArrowButton.tsx
> +			className={clsx(styles.container, {[styles.container_open]: isOpenForm})}
dk e

2024-05-04 19:14 UTC, Atasik commented on src/components/arrow-button/ArrowButton.tsx
> +				e.stopPropagation()
done

2024-05-04 19:14 UTC, Atasik commented on src/index.tsx
>  			className={clsx(styles.main)}
done

2024-05-04 19:14 UTC, Atasik commented on src/index.tsx
>  const App = () => {
done

2024-05-04 19:14 UTC, Atasik commented on src/components/article-params-form/ArticleParamsForm.tsx
> +					onSubmit={formSubmitHandler}
done

2024-05-04 19:14 UTC, Atasik commented on src/components/article-params-form/ArticleParamsForm.tsx
> +				ref={rootRef}
done

2024-05-04 19:14 UTC, Atasik commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const formSubmitHandler = (e: SyntheticEvent) => {
done

2024-05-04 19:14 UTC, Atasik commented on src/components/article-params-form/ArticleParamsForm.tsx
> +		setNewFontColor(fontColors[0]);
done

2024-05-04 19:14 UTC, Atasik commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	useOutsideClickClose({
done

2024-05-04 19:15 UTC, Atasik commented
Я честно попытался попользоваться через пре хуки, но когда мне заресетило весь коммит, я решил, что stories я править не буду через линтер)

2024-05-05 02:01 UTC, olgalatkina requested changes
Здравствуйте.
Отличный рефакторинг!

**Осталось доработать совсем немного:**
- [ ] В реф нужно получить доступ к внешнему диву, который заменит `React.Fragment`. Вернуть обратно тег `aside`.
- [ ] Заменить тип `any` на подходящий.

Замечания **можно лучше** остаются на ваше усмотрение:
- [ ] Запустить полезные скрипты из package.json. Удалить неиспользуемые импорты   в проекте. 
- [ ] Избавиться от горизонтальной прокрутки в сайдбаре на небольших экранах.

Успешного рефакторинга!

2024-05-05 02:01 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +				ref={rootRef}
1. Нужно было сначала определиться, где у вас в коде `React.Fragment` Надеюсь, документация вам с этим поможет: https://react.dev/reference/react/Fragment
2. Затем заменить его на `div`
3. Получить доступ к этому диву при помощи `ref`, т.е. перенести реф с `aside` на этот внешний `div`
4. Теперь вернём на место `aside`, его вообще не надо было трогать.

2024-05-05 02:01 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +			onClick={(e: SyntheticEvent) => {
**Можно лучше:**
В обработчике больше не используется событие - его лучше удалить. И не забудьте так же удалить неиспользуемые импорты.
В package.json есть достаточной большой набор скриптов, которые помогут найти ошибки литера, а так же отформатировать код.
Ошибки, которые пришли со стартер-китом можно не исправлять.

2024-05-05 02:01 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +	background-color: #ffffff;
**Отлично:**
Здорово, что смогли найти оптимальное решение.
Если в `.form` ширину сделать 100%, то уйдёт горизонтальная прокрутка.

2024-05-05 02:01 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	setCurrentArticleState: (params: any) => void;
**Надо исправить:**
Тип `any` не используется без необходимости.

2024-05-05 06:59 UTC, Atasik commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	setCurrentArticleState: (params: any) => void;
done

2024-05-05 06:59 UTC, Atasik commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +	background-color: #ffffff;
done

2024-05-05 06:59 UTC, Atasik commented on src/components/arrow-button/ArrowButton.tsx
> +			onClick={(e: SyntheticEvent) => {
done

2024-05-05 11:35 UTC, olgalatkina reviewed
Добрый день.

**Отличная работа! Проект принимается**🎉

Успехов в дальнейшем обучении!

2024-05-05 20:51 UTC, merged